### ISSUE TITLE
ng6 support

### ISSUE THREAD

**Issue by realgsong** [lfarran/ngx-soundmanager2#10]
I'm trying to apply ng6. ngx-soundmanager2 failed to be built with following error.

```
node_modules/ngx-soundmanager2/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
```

It's caused by unmatched angular/core of ngx-soundmanager/node_modules and ./node_modules. If I remove it, build goes well.(Not tested yet)

**Comment by lfarran** [comment]
Merged, thanks @realgsong!
