### ISSUE TITLE
Create Demo Page

### ISSUE THREAD

**Issue by lfarran** [lfarran/ngx-soundmanager2#2]
Create Demo Page to show usage of module.

**Comment by Iraecio** [comment]
Really need a demo page I'm trying to play an online radio but add the url adds to the list but play does not play and even the service saying it's playing...

**Comment by lfarran** [comment]
Hi Iraecio, while the demo page is being worked on, let me know if the code examples below help. 

**In Angular Component HTML Template:**
            <div class="row">
              <div class="col-md-12">
                <h5>Songs</h5>
                <div *ngFor="let song of songs">
                  <span>
                    <button class="btn btn-default" [musicPlayer]="'play'" [song]="song">{{ song.title }}</button>
                    <button class="btn btn-default" musicPlayer [song]="song">+</button>
                  </span>
                </div>

                <div>
                  <span>
                    <button class="btn btn-default" playAll [songs]="songs">Play all</button>
                    <button class="btn btn-default" playAll [songs]="songs" [play]="false">Add all</button>
                  </span>
                </div>
              </div>
            </div>

            <hr />

            <div class="row">
              <div class="col-md-12">
                <p *ngIf="currentPlaying">
                  Currently Playing: {{ currentPlaying.title }} by {{ currentPlaying.artist }} ({{ currentTrackPostion | humanTime }} / {{ currentTrackDuration | humanTime }})
                </p>

                <div class="progress" style="height: 20px; width: 100%;">
                  <div class="progress-bar progress-bar-success"
                       role="progressbar"
                       [ngStyle]="{width : progress }">
                    <span class="sr-only"></span>
                  </div>
                </div>

                <div>
                  <span>
                    <button class="btn btn-default" playMusic>
                      <i class="fa fa-play" aria-hidden="true"></i>
                    </button>
                    <button class="btn btn-default" pauseMusic>
                      <i class="fa fa-pause" aria-hidden="true"></i>
                    </button>
                    <button class="btn btn-default" stopMusic>
                      <i class="fa fa-stop" aria-hidden="true"></i>
                    </button>
                  </span>
                </div>
                <button class="btn btn-default" repeatMusic>Repeat</button>
                
                

                

                <h5>Volume: {{ volume }}</h5>

                <button class="btn btn-default" increaseVolume>+</button>
                <button class="btn btn-default" decreaseVolume>-</button>
                <button class="btn btn-default" muteMusic>Mute ({{ mute }})</button>

                <div>
                  <span>
                    <button class="btn btn-default" previousTrack>
                      <i class="fa fa-step-backward" aria-hidden="true"></i>
                    </button>
                    <button class="btn btn-default" nextTrack>
                      <i class="fa fa-step-forward" aria-hidden="true"></i>
                    </button>
                    <button class="btn btn-default" clearPlaylist>Clear Playlist</button>
                  </span>
                </div>

                <h5>Playlist</h5>
                <ul>
                  <li *ngFor="let song of playlist; index as i;">
                    <a playFromPlaylist [song]="song">{{ song.title }}</a>
                    <a removeFromPlaylist [song]="song" [index]="i">
                      <small>(remove)</small>
                    </a>
                    <span *ngIf="currentPlaying && currentPlaying.id == song.id"> - (current)</span>
                  </li>
                </ul>
              </div>
            </div>

         
 **Angular Component:**
import { Component, HostBinding, OnInit, OnDestroy } from '@angular/core';

// app
import { MusicPlayerService } from '../shared/ngx-soundmanager2/music-player.service';

@Component({
  moduleId: module.id,
  selector: 'lf-demo',
  templateUrl: './some.component.html',
  animations: [routerTransition]
})
export class SomeComponent implements OnInit, OnDestroy {

  songs = [
    {
      id: 'one',
      title: 'Rain',
      artist: 'Drake',
      url: 'http://www.schillmania.com/projects/soundmanager2/demo/_mp3/rain.mp3'
    },
    {
      id: 'two',
      title: 'Walking',
      artist: 'Nicki Minaj',
      url: 'http://www.schillmania.com/projects/soundmanager2/demo/_mp3/walking.mp3'
    },
    {
      id: 'three',
      title: 'Barrlping with Carl (featureblend.com)',
      artist: 'Akon',
      url: 'http://www.freshly-ground.com/misc/music/carl-3-barlp.mp3'
    },
    {
      id: 'four',
      title: 'Angry cow sound?',
      artist: 'A Cow',
      url: 'http://www.freshly-ground.com/data/audio/binaural/Mak.mp3'
    },
    {
      id: 'five',
      title: 'Things that open, close and roll',
      artist: 'Someone',
      url: 'http://www.freshly-ground.com/data/audio/binaural/Things%20that%20open,%20close%20and%20roll.mp3'
    }
  ];

  mute: boolean;
  currentPlaying: any;
  currentTrackPostion: number;
  currentTrackDuration: number;
  currentTrackProgress: number;
  volume: number;

  // subscriptions
  private _musicPlayerMuteSubscription: any;
  private _musicPlayerTrackIdSubscription: any;
  private _musicPlayerVolumeSubscription: any;

  constructor(private _musicPlayerService: MusicPlayerService) {}

  ngOnInit() {
    // Subscribe for mute changes to update bindings
    this.mute = this._musicPlayerService.getMuteStatus();
    this._musicPlayerMuteSubscription = this._musicPlayerService.musicPlayerMuteEventEmitter
      .subscribe((event: any) => {
        this.mute = event.data;
      });

    // Subscribe for track changes
    this.currentPlaying = this._musicPlayerService.currentTrackData();
    this._musicPlayerTrackIdSubscription = this._musicPlayerService.musicPlayerTrackEventEmitter
      .subscribe((event: any) => {
        this.currentPlaying = this._musicPlayerService.currentTrackData();
        this.currentTrackPostion = event.data.trackPosition;
        this.currentTrackDuration = event.data.trackDuration;
        this.currentTrackProgress = event.data.trackProgress;
      });

    // subscribe for volume changes
    this.volume = this._musicPlayerService.getVolume();
    this._musicPlayerVolumeSubscription = this._musicPlayerService.musicPlayerVolumeEventEmitter
      .subscribe((event: any) => {
        this.volume = event.data;
      });
  }

  ngOnDestroy() {
    this._musicPlayerMuteSubscription.unsubscribe();
    this._musicPlayerTrackIdSubscription.unsubscribe();
    this._musicPlayerVolumeSubscription.unsubscribe();
  }

  get progress(): string {
    return this.currentTrackProgress ? (this.currentTrackProgress.toString() + '%') : '0%';
  }

  get playlist(): any {
    return this._musicPlayerService.getPlaylist();
  }
}

**Comment by Iraecio** [comment]
My problem is whit Streaming Radio station!

i make two function in service and work

`
streamPlayer: any;
createStream(url: string = null) {
		if (url !== null) {
			this.streamPlayer = soundManager.createSound({
				id: "EnauanSm2",
				serverUrl: url,
				url: url,
				useHTML5Audio: true,
				stream: true,
				usePeakData: true,
				usePolicyFile: true,
				onresume: function () {
					console.log("onresume");
				},
				onfinish: function () {
					console.log("finish");
				},
				unload: function (e) {
					console.log(e);
				},
				onpause: function (e) {
					console.log(e);
				},
				onplay: function () {
					console.log('play');
				},
				onload: function () {
					console.log('The sound ' + this.id + ' loaded!');
				}
			});
		}
	}

	playStream():void{
		this.streamPlayer.play();
	}
	
	stopStream():void{
		soundManager.pause(this.streamPlayer);
		soundManager.unload(this.streamPlayer);
	}
`

**Comment by swapniprakashpatil** [comment]
Any update on demo page?

**Comment by swapniprakashpatil** [comment]
Parminder Klair's demo page was great example. Can you please provide demo page similar to that?

**Comment by lfarran** [comment]
@swapniprakashpatil now that I know that there's some interest, I'll bump this up in my queue.  In the meantime, please see my comments above in this thread from 8/20 on how to use it.

**Comment by swapniprakashpatil** [comment]
Hey @lfarran  I did tried implementing your code from the thread 8/20 with fresh app from angular-cli. But I am getting error  "soundManager is not defined" with the alert box. I later explicitly installed soundmanager2  as well but no luck.

Steps I did:
1. new app from angular-cli
2. npm install  ngx-soundmanager2 and bootstrap
4. configured angular-cli.json to include bootstrap.js, bootstrap.css in scripts and styles from node_modules
5. configured angular-cli.json to include ngx-soundmanager2/lib/index.ts
6. Used component code from 8/20 thread in app.component.ts
7. Used html code from 8/20 thread in app.component.html
8. Added dependency for NgxSoundmanager2Module and MusicPlayerService in app.module.ts

Will wait for your demo page.

**Comment by swapniprakashpatil** [comment]
@lfarran  Do you mind adding example for playing track using stream?

**Comment by lfarran** [comment]
@swapniprakashpatil I'm looking into the issues listed below and I'll will add examples in the demo.

**Comment by lfarran** [comment]
@swapniprakashpatil I made some updates to the build steps so that the ngx-soundmanager2 so that you shouldn't need to explicitly move the files to the app.  I added a demo page that can be ran too.  

Can you provide an example of a stream that you need an example for?
