### ISSUE TITLE
AOT Build Issue

### ISSUE THREAD

**Issue by lfarran** [lfarran/ngx-soundmanager2#7]
Error: Error encountered resolving symbol values statically. Calling function 'NgxSoundmanager2Module', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol SharedModule in /dist/tmp/app/shared/shared.module.ts, resolving symbol SharedModule in /dist/tmp/app/shared/shared.module.ts

**Comment by lfarran** [comment]
Reference: https://github.com/angular/angular/issues/14707

**Comment by realgsong** [comment]
I built ngx-soundmanager2 with angular-library-starter https://github.com/robisim74/angular-library-starter and it works well! I'll create a pull request.

**Comment by lfarran** [comment]
Thanks @realgsong!!!
